spring:
  profiles:
    active: local
  application:
    name: counsel-service

  datasource:
    url: jdbc:mysql://localhost:3307/counsel_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000

  data:
    redis:
      host: localhost
      port: 6379
      password: your_secure_password_2025!xAiRedisCounselingService
      timeout: 2000
      lettuce:
        pool:
          max-active: 50
          max-idle: 10
          min-idle: 5

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: false
        use_sql_comments: true
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: xFFbtD5AcGOgGSNIPYt1
            client-secret: z26Y1Je6cR
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: email,name
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: 7f8a9b0c1d2e3f4g5h6i7j8k9l0m1n2o3p4q5r6s7t8u9v0w1x2y3z4a5b6c7d8e9f
  token-validity-seconds: 3600 #1시간
  refresh-token-validity-seconds: 86400

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

#logging:
#  level:
#    root: INFO
#    com.harry.counsel: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.springframework.web: INFO
#    org.springframework.security: INFO
#    org.springframework.data.redis: DEBUG

websocket:
  allowed-origins: "*"
  endpoint: /ws
  destination-prefixes: /app
  broker-prefixes: /topic, /queue