spring:
  profiles:
    active: local
  application:
    name: counsel-service

  datasource:
    url: jdbc:mysql://localhost:3306/counsel_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
    open-in-view: false


server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: your-secret-key-must-be-at-least-256-bits-long-for-security-reasons
  token-validity-seconds: 3600 #1시간
  refresh-token-validity-seconds: 86400

logging:
  level:
    root: INFO
    com.harry.counsel: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.data.redis: DEBUG

websocket:
  allowed-origins: "*"
  endpoint: /ws
  destination-prefixes: /app
  broker-prefixes: /topic, /queue


